In [ ]:
from sklearn.metrics import accuracy_score, precision_score, f1_score, recall_score
from sklearn.ensemble import GradientBoostingClassifier, VotingClassifier, StackingClassifier, AdaBoostClassifier, RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split
import pandas as pd

In [2]:
df = pd.read_csv("../Data-Files/novagen_dataset.csv")
df.head()

,Age,BMI,Blood_Pressure,Cholesterol,Glucose_Level,Heart_Rate,Sleep_Hours,Exercise_Hours,Water_Intake,Stress_Level,...,Diet,MentalHealth,PhysicalActivity,MedicalHistory,Allergies,Diet_Type__Vegan,Diet_Type__Vegetarian,Blood_Group_AB,Blood_Group_B,Blood_Group_O
0,2.0,26.0,111.0,198.0,99.0,72.0,4.0,1.0,5.0,5.0,...,1,2,1,0,1,False,True,True,False,False
1,8.0,24.0,121.0,199.0,103.0,75.0,2.0,1.0,2.0,9.0,...,1,2,1,2,2,False,False,True,False,False
2,81.0,27.0,147.0,203.0,100.0,74.0,10.0,-0.0,5.0,1.0,...,2,0,0,1,0,True,False,False,False,False
3,25.0,21.0,150.0,199.0,102.0,70.0,7.0,3.0,3.0,3.0,...,1,2,1,2,0,True,False,False,True,False
4,24.0,26.0,146.0,202.0,99.0,76.0,10.0,2.0,5.0,1.0,...,2,0,2,0,2,False,True,False,True,False

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9549 entries, 0 to 9548
Data columns (total 23 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Age                    9549 non-null   float64
 1   BMI                    9549 non-null   float64
 2   Blood_Pressure         9549 non-null   float64
 3   Cholesterol            9549 non-null   float64
 4   Glucose_Level          9549 non-null   float64
 5   Heart_Rate             9549 non-null   float64
 6   Sleep_Hours            9549 non-null   float64
 7   Exercise_Hours         9549 non-null   float64
 8   Water_Intake           9549 non-null   float64
 9   Stress_Level           9549 non-null   float64
 10  Target                 9549 non-null   int64
 11  Smoking                9549 non-null   int64
 12  Alcohol                9549 non-null   int64
 13  Diet                   9549 non-null   int64
 14  MentalHealth           9549 non-null   int64
 15  PhysicalActivity       9549 non-null   int64
 16  MedicalHistory         9549 non-null   int64
 17  Allergies              9549 non-null   int64
 18  Diet_Type__Vegan       9549 non-null   bool
 19  Diet_Type__Vegetarian  9549 non-null   bool
 20  Blood_Group_AB         9549 non-null   bool
 21  Blood_Group_B          9549 non-null   bool
 22  Blood_Group_O          9549 non-null   bool
dtypes: bool(5), float64(10), int64(8)
memory usage: 1.4 MB

In [9]:
print(df.columns)
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
features = ['Diet_Type__Vegan','Diet_Type__Vegetarian', 'Blood_Group_AB', 'Blood_Group_B', 'Blood_Group_O']
df[features] = df[features].apply(le.fit_transform)
df.head()

Index(['Age', 'BMI', 'Blood_Pressure', 'Cholesterol', 'Glucose_Level',
       'Heart_Rate', 'Sleep_Hours', 'Exercise_Hours', 'Water_Intake',
       'Stress_Level', 'Target', 'Smoking', 'Alcohol', 'Diet', 'MentalHealth',
       'PhysicalActivity', 'MedicalHistory', 'Allergies', 'Diet_Type__Vegan',
       'Diet_Type__Vegetarian', 'Blood_Group_AB', 'Blood_Group_B',
       'Blood_Group_O'],
      dtype='object')

,Age,BMI,Blood_Pressure,Cholesterol,Glucose_Level,Heart_Rate,Sleep_Hours,Exercise_Hours,Water_Intake,Stress_Level,...,Diet,MentalHealth,PhysicalActivity,MedicalHistory,Allergies,Diet_Type__Vegan,Diet_Type__Vegetarian,Blood_Group_AB,Blood_Group_B,Blood_Group_O
0,2.0,26.0,111.0,198.0,99.0,72.0,4.0,1.0,5.0,5.0,...,1,2,1,0,1,0,1,1,0,0
1,8.0,24.0,121.0,199.0,103.0,75.0,2.0,1.0,2.0,9.0,...,1,2,1,2,2,0,0,1,0,0
2,81.0,27.0,147.0,203.0,100.0,74.0,10.0,-0.0,5.0,1.0,...,2,0,0,1,0,1,0,0,0,0
3,25.0,21.0,150.0,199.0,102.0,70.0,7.0,3.0,3.0,3.0,...,1,2,1,2,0,1,0,0,1,0
4,24.0,26.0,146.0,202.0,99.0,76.0,10.0,2.0,5.0,1.0,...,2,0,2,0,2,0,1,0,1,0

In [12]:
num_corr = df.select_dtypes(include=["number"])
corr = num_corr.corr()
corr["Target"].sort_values(ascending=False)

Target                   1.000000
BMI                      0.413972
Stress_Level             0.119455
Sleep_Hours              0.025931
Diet_Type__Vegan         0.023707
Exercise_Hours           0.008214
Blood_Group_B            0.007749
Diet                     0.005602
Alcohol                  0.003077
Blood_Group_AB           0.001174
MedicalHistory          -0.001666
PhysicalActivity        -0.002511
Blood_Group_O           -0.002728
Allergies               -0.004322
Diet_Type__Vegetarian   -0.005176
Smoking                 -0.005283
MentalHealth            -0.016372
Water_Intake            -0.038406
Heart_Rate              -0.065957
Glucose_Level           -0.072148
Age                     -0.190743
Cholesterol             -0.324361
Blood_Pressure          -0.380279
Name: Target, dtype: float64

In [13]:
features = ["BMI", "Cholesterol", "Blood_Pressure"]
df[features] = df[features] * 2
df.head()

,Age,BMI,Blood_Pressure,Cholesterol,Glucose_Level,Heart_Rate,Sleep_Hours,Exercise_Hours,Water_Intake,Stress_Level,...,Diet,MentalHealth,PhysicalActivity,MedicalHistory,Allergies,Diet_Type__Vegan,Diet_Type__Vegetarian,Blood_Group_AB,Blood_Group_B,Blood_Group_O
0,2.0,52.0,222.0,396.0,99.0,72.0,4.0,1.0,5.0,5.0,...,1,2,1,0,1,0,1,1,0,0
1,8.0,48.0,242.0,398.0,103.0,75.0,2.0,1.0,2.0,9.0,...,1,2,1,2,2,0,0,1,0,0
2,81.0,54.0,294.0,406.0,100.0,74.0,10.0,-0.0,5.0,1.0,...,2,0,0,1,0,1,0,0,0,0
3,25.0,42.0,300.0,398.0,102.0,70.0,7.0,3.0,3.0,3.0,...,1,2,1,2,0,1,0,0,1,0
4,24.0,52.0,292.0,404.0,99.0,76.0,10.0,2.0,5.0,1.0,...,2,0,2,0,2,0,1,0,1,0

In [14]:
X = df.drop(columns=["Target"])
y = df["Target"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

In [ ]:
from sklearn.model_selection import GridSearchCV
from sklearn.pipeline import Pipeline
from sklearn.metrics import confusion_matrix

rf_pipeline = Pipeline([
    ("rf", RandomForestClassifier())
])

param_grid = [{
    "rf__n_estimators": [101, 201, 301, 401, 501], 
    # "rf__criterion": ["gini", "entropy", "log_loss"],
    "rf__max_depth": [3, 4, 5, 6, 7],
    "rf__min_samples_split": [2, 5, 9, 12, 15]
}]

classiferCV = GridSearchCV(
    estimator=rf_pipeline,
    param_grid=param_grid,
    cv=5,
    return_train_score=True,
    n_jobs=-1
)

classiferCV.fit(X_train, y_train)

y_pred = classiferCV.predict(X_test)

print("Accuracy:\t", accuracy_score(y_test, y_pred))
print("Recall:\t",  recall_score(y_test, y_pred))
print("Precision:\t", precision_score(y_test, y_pred))
print("F1 Scorce:\t", f1_score(y_test, y_pred))
print("CM:\n", confusion_matrix(y_test, y_pred))

res = pd.DataFrame(classiferCV.cv_results_)

print(classiferCV.best_params_)

Accuracy:	 0.8926701570680629
Recall:	 0.9327309236947792
Precision:	 0.8706654170571696
F1 Scorce:	 0.900630150266602
CM:
 [[776 138]
 [ 67 929]]
{'rf__max_depth': 7, 'rf__min_samples_split': 12, 'rf__n_estimators': 101}

In [22]:
gbc_pipeline = Pipeline([
    ("gbc", GradientBoostingClassifier())
])

param_grid = [{
    "gbc__n_estimators": [101, 201, 301, 401, 501], 
    # "rf__criterion": ["gini", "entropy", "log_loss"],
    "gbc__max_depth": [3, 4, 5, 6, 7],
    "gbc__min_samples_split": [2, 5, 9, 12, 15]
}]

classiferCV = GridSearchCV(
    estimator=gbc_pipeline,
    param_grid=param_grid,
    cv=5,
    return_train_score=True,
    n_jobs=-1
)

classiferCV.fit(X_train, y_train)

y_pred = classiferCV.predict(X_test)

print("Accuracy:\t", accuracy_score(y_test, y_pred))
print("Recall:\t",  recall_score(y_test, y_pred))
print("Precision:\t", precision_score(y_test, y_pred))
print("F1 Scorce:\t", f1_score(y_test, y_pred))
print("CM:\n", confusion_matrix(y_test, y_pred))

res = pd.DataFrame(classiferCV.cv_results_)

print(classiferCV.best_params_)

Accuracy:	 0.9528795811518325
Recall:	 0.963855421686747
Precision:	 0.9467455621301775
F1 Scorce:	 0.9552238805970149
CM:
 [[860  54]
 [ 36 960]]
{'gbc__max_depth': 7, 'gbc__min_samples_split': 15, 'gbc__n_estimators': 501}

In [ ]:
abc_pipeline = Pipeline([
    ("abc", AdaBoostClassifier())
])

param_grid = [{
    "abc__n_estimators": [101, 201, 301, 401, 501], 
    # "rf__criterion": ["gini", "entropy", "log_loss"],
    "abc__learning_rate": [0.001, 0.01, 0.1, 2, 3],
    "abc__estimator": [DecisionTreeClassifier, SVC, GaussianNB, LogisticRegression]
}]

classiferCV = GridSearchCV(
    estimator=abc_pipeline,
    param_grid=param_grid,
    cv=5,
    return_train_score=True,
    n_jobs=-1
)

classiferCV.fit(X_train, y_train)

y_pred = classiferCV.predict(X_test)

print("Accuracy:\t", accuracy_score(y_test, y_pred))
print("Recall:\t",  recall_score(y_test, y_pred))
print("Precision:\t", precision_score(y_test, y_pred))
print("F1 Scorce:\t", f1_score(y_test, y_pred))
print("CM:\n", confusion_matrix(y_test, y_pred))

res = pd.DataFrame(classiferCV.cv_results_)

print(classiferCV.best_params_)