In [1]:
import pandas as pd
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score
from sklearn.tree import DecisionTreeClassifier

In [2]:
df = pd.read_csv("../Data-Files/shop_smart_ecommerce.csv")
df.head()

,Administrative,Administrative_Duration,Informational,Informational_Duration,ProductRelated,ProductRelated_Duration,BounceRates,ExitRates,PageValues,SpecialDay,Month,OperatingSystems,Browser,Region,TrafficType,VisitorType,Weekend,Revenue
0,0,0.0,0,0.0,1,0.000000,0.20,0.20,0.0,0.0,Feb,1,1,1,1,Returning_Visitor,False,False
1,0,0.0,0,0.0,2,64.000000,0.00,0.10,0.0,0.0,Feb,2,2,1,2,Returning_Visitor,False,False
2,0,0.0,0,0.0,1,0.000000,0.20,0.20,0.0,0.0,Feb,4,1,9,3,Returning_Visitor,False,False
3,0,0.0,0,0.0,2,2.666667,0.05,0.14,0.0,0.0,Feb,3,2,2,4,Returning_Visitor,False,False
4,0,0.0,0,0.0,10,627.500000,0.02,0.05,0.0,0.0,Feb,3,3,1,4,Returning_Visitor,True,False

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12330 entries, 0 to 12329
Data columns (total 18 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Administrative           12330 non-null  int64
 1   Administrative_Duration  12330 non-null  float64
 2   Informational            12330 non-null  int64
 3   Informational_Duration   12330 non-null  float64
 4   ProductRelated           12330 non-null  int64
 5   ProductRelated_Duration  12330 non-null  float64
 6   BounceRates              12330 non-null  float64
 7   ExitRates                12330 non-null  float64
 8   PageValues               12330 non-null  float64
 9   SpecialDay               12330 non-null  float64
 10  Month                    12330 non-null  object
 11  OperatingSystems         12330 non-null  int64
 12  Browser                  12330 non-null  int64
 13  Region                   12330 non-null  int64
 14  TrafficType              12330 non-null  int64
 15  VisitorType              12330 non-null  object
 16  Weekend                  12330 non-null  bool
 17  Revenue                  12330 non-null  bool
dtypes: bool(2), float64(7), int64(7), object(2)
memory usage: 1.5+ MB

In [4]:
df.describe()

,Administrative,Administrative_Duration,Informational,Informational_Duration,ProductRelated,ProductRelated_Duration,BounceRates,ExitRates,PageValues,SpecialDay,OperatingSystems,Browser,Region,TrafficType
count,12330.000000,12330.000000,12330.000000,12330.000000,12330.000000,12330.000000,12330.000000,12330.000000,12330.000000,12330.000000,12330.000000,12330.000000,12330.000000,12330.000000
mean,2.315166,80.818611,0.503569,34.472398,31.731468,1194.746220,0.022191,0.043073,5.889258,0.061427,2.124006,2.357097,3.147364,4.069586
std,3.321784,176.779107,1.270156,140.749294,44.475503,1913.669288,0.048488,0.048597,18.568437,0.198917,0.911325,1.717277,2.401591,4.025169
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,1.000000
25%,0.000000,0.000000,0.000000,0.000000,7.000000,184.137500,0.000000,0.014286,0.000000,0.000000,2.000000,2.000000,1.000000,2.000000
50%,1.000000,7.500000,0.000000,0.000000,18.000000,598.936905,0.003112,0.025156,0.000000,0.000000,2.000000,2.000000,3.000000,2.000000
75%,4.000000,93.256250,0.000000,0.000000,38.000000,1464.157214,0.016813,0.050000,0.000000,0.000000,3.000000,2.000000,4.000000,4.000000
max,27.000000,3398.750000,24.000000,2549.375000,705.000000,63973.522230,0.200000,0.200000,361.763742,1.000000,8.000000,13.000000,9.000000,20.000000

In [5]:
df.isna().sum()

Administrative             0
Administrative_Duration    0
Informational              0
Informational_Duration     0
ProductRelated             0
ProductRelated_Duration    0
BounceRates                0
ExitRates                  0
PageValues                 0
SpecialDay                 0
Month                      0
OperatingSystems           0
Browser                    0
Region                     0
TrafficType                0
VisitorType                0
Weekend                    0
Revenue                    0
dtype: int64

In [6]:
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
df["Revenue"] = le.fit_transform(df["Revenue"])
df["Weekend"] = le.fit_transform(df["Weekend"])
df.head()
# class_count = df["Revenue"].value_counts()
# class_count
# plt.pie(class_count, labels=["No", "Yes"],  autopct="%1.1f%%")

,Administrative,Administrative_Duration,Informational,Informational_Duration,ProductRelated,ProductRelated_Duration,BounceRates,ExitRates,PageValues,SpecialDay,Month,OperatingSystems,Browser,Region,TrafficType,VisitorType,Weekend,Revenue
0,0,0.0,0,0.0,1,0.000000,0.20,0.20,0.0,0.0,Feb,1,1,1,1,Returning_Visitor,0,0
1,0,0.0,0,0.0,2,64.000000,0.00,0.10,0.0,0.0,Feb,2,2,1,2,Returning_Visitor,0,0
2,0,0.0,0,0.0,1,0.000000,0.20,0.20,0.0,0.0,Feb,4,1,9,3,Returning_Visitor,0,0
3,0,0.0,0,0.0,2,2.666667,0.05,0.14,0.0,0.0,Feb,3,2,2,4,Returning_Visitor,0,0
4,0,0.0,0,0.0,10,627.500000,0.02,0.05,0.0,0.0,Feb,3,3,1,4,Returning_Visitor,1,0

In [7]:
num_cols = df.select_dtypes(include="number")
corr_matrix = num_cols.corr()
corr_matrix["Revenue"].sort_values(ascending=False)

Revenue                    1.000000
PageValues                 0.492569
ProductRelated             0.158538
ProductRelated_Duration    0.152373
Administrative             0.138917
Informational              0.095200
Administrative_Duration    0.093587
Informational_Duration     0.070345
Weekend                    0.029295
Browser                    0.023984
TrafficType               -0.005113
Region                    -0.011595
OperatingSystems          -0.014668
SpecialDay                -0.082305
BounceRates               -0.150673
ExitRates                 -0.207071
Name: Revenue, dtype: float64

In [8]:
from sklearn.preprocessing import OneHotEncoder

ohe = OneHotEncoder(drop="first", sparse_output=False, handle_unknown="ignore")
cols = ["VisitorType", "Month"]

encoded = ohe.fit_transform(df[cols])
encoded_df = pd.DataFrame(encoded, columns=ohe.get_feature_names_out(cols), index=df.index)
df = pd.concat([df.drop(columns=cols), encoded_df], axis=1)

df.head()

,Administrative,Administrative_Duration,Informational,Informational_Duration,ProductRelated,ProductRelated_Duration,BounceRates,ExitRates,PageValues,SpecialDay,...,VisitorType_Returning_Visitor,Month_Dec,Month_Feb,Month_Jul,Month_June,Month_Mar,Month_May,Month_Nov,Month_Oct,Month_Sep
0,0,0.0,0,0.0,1,0.000000,0.20,0.20,0.0,0.0,...,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0,0.0,0,0.0,2,64.000000,0.00,0.10,0.0,0.0,...,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0,0.0,0,0.0,1,0.000000,0.20,0.20,0.0,0.0,...,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0,0.0,0,0.0,2,2.666667,0.05,0.14,0.0,0.0,...,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0,0.0,0,0.0,10,627.500000,0.02,0.05,0.0,0.0,...,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [9]:
num_cols = df.select_dtypes(include="number")
corr_matrix = num_cols.corr()
corr_matrix["Revenue"].sort_values(ascending=False)

Revenue                          1.000000
PageValues                       0.492569
ProductRelated                   0.158538
Month_Nov                        0.154774
ProductRelated_Duration          0.152373
Administrative                   0.138917
Informational                    0.095200
Administrative_Duration          0.093587
Informational_Duration           0.070345
Month_Oct                        0.032666
Weekend                          0.029295
Browser                          0.023984
Month_Sep                        0.019983
VisitorType_Other                0.007715
Month_Jul                       -0.001036
TrafficType                     -0.005113
Region                          -0.011595
OperatingSystems                -0.014668
Month_June                      -0.023112
Month_Dec                       -0.033112
Month_Feb                       -0.047114
Month_Mar                       -0.063941
Month_May                       -0.078320
SpecialDay                      -0.082305
VisitorType_Returning_Visitor   -0.103843
BounceRates                     -0.150673
ExitRates                       -0.207071
Name: Revenue, dtype: float64

In [10]:
from sklearn.model_selection import train_test_split
features = ["PageValues", "ProductRelated", "ExitRates", "BounceRates", "VisitorType_Returning_Visitor", "Month_Nov", "ProductRelated_Duration"]
target = ["Revenue"]

X = df[features]
y = df[target]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
X_train.head()

,PageValues,ProductRelated,ExitRates,BounceRates,VisitorType_Returning_Visitor,Month_Nov,ProductRelated_Duration
1785,0.000000,7,0.061905,0.014286,1.0,0.0,95.000000
10407,2.769599,81,0.013933,0.002469,1.0,1.0,1441.910588
286,0.000000,1,0.200000,0.200000,1.0,0.0,0.000000
6520,8.326728,5,0.018182,0.000000,0.0,0.0,74.600000
12251,0.000000,9,0.041667,0.040000,0.0,1.0,279.000000

In [11]:
model = DecisionTreeClassifier()
model.fit(X_train, y_train)

DecisionTreeClassifier()

In [12]:
y_pred = model.predict(X_test)

print("Accuracy:\t", accuracy_score(y_test, y_pred))
print("Recall:\t",  recall_score(y_test, y_pred))
print("Precision:\t", precision_score(y_test, y_pred))
print("F1 Scorce:\t", f1_score(y_test, y_pred))
print("CM:\n", confusion_matrix(y_test, y_pred))

Accuracy:	 0.8576642335766423
Recall:	 0.5693430656934306
Precision:	 0.5735294117647058
F1 Scorce:	 0.5714285714285714
CM:
 [[1881  174]
 [ 177  234]]

In [13]:
path = model.cost_complexity_pruning_path(X_train, y_train)
ccps = path.ccp_alphas
ccps

array([0.00000000e+00, 6.84156496e-08, 2.22525153e-07, 3.80353178e-07,
       3.92700565e-07, 4.09611115e-06, 7.95435738e-06, 3.37929170e-05,
       3.37929170e-05, 5.06893755e-05, 5.06893755e-05, 5.56589221e-05,
       6.08272506e-05, 6.33617194e-05, 6.43674610e-05, 6.45137506e-05,
       6.48824006e-05, 6.52552880e-05, 6.53329729e-05, 6.55377784e-05,
       6.55980154e-05, 6.61478375e-05, 6.62221166e-05, 6.65460519e-05,
       6.68443671e-05, 6.73975726e-05, 6.74016764e-05, 6.78636288e-05,
       7.52379506e-05, 7.60340633e-05, 7.60340633e-05, 7.60340633e-05,
       7.81949785e-05, 8.11030008e-05, 8.11030008e-05, 8.11030008e-05,
       8.11030008e-05, 8.35962215e-05, 8.39337062e-05, 8.44822925e-05,
       8.44822925e-05, 8.49542163e-05, 8.59993120e-05, 8.64998896e-05,
       8.68960723e-05, 8.68960723e-05, 8.68960723e-05, 8.68960723e-05,
       8.68960723e-05, 8.87064071e-05, 8.87064071e-05, 8.87064071e-05,
       8.87064071e-05, 8.93098521e-05, 8.94518391e-05, 9.01144453e-05,
       9.01144453e-05, 9.01972711e-05, 9.10284378e-05, 9.12408759e-05,
       9.12408759e-05, 9.12408759e-05, 9.12408759e-05, 9.12408759e-05,
       9.12408759e-05, 9.12408759e-05, 9.24335671e-05, 9.28646914e-05,
       9.29305218e-05, 9.29305218e-05, 9.29305218e-05, 9.29305218e-05,
       9.35803856e-05, 9.35803856e-05, 9.35803856e-05, 9.35803856e-05,
       9.36840872e-05, 9.41374117e-05, 9.41374117e-05, 9.41374117e-05,
       9.41374117e-05, 9.41890293e-05, 9.42253631e-05, 9.46201676e-05,
       9.46201676e-05, 9.46201676e-05, 9.50425791e-05, 9.50425791e-05,
       9.51029236e-05, 9.54152951e-05, 9.58000342e-05, 9.58490010e-05,
       9.58910124e-05, 9.60430273e-05, 9.65047726e-05, 9.65511914e-05,
       9.67706260e-05, 9.67706260e-05, 9.74584916e-05, 9.76239825e-05,
       9.77580813e-05, 9.81084687e-05, 9.81084687e-05, 9.83066676e-05,
       9.88979318e-05, 9.90211056e-05, 9.96308415e-05, 9.96308415e-05,
       9.96308415e-05, 9.99304831e-05, 1.00125543e-04, 1.00127161e-04,
       1.00367422e-04, 1.01317212e-04, 1.01378751e-04, 1.01378751e-04,
       1.01378751e-04, 1.01378751e-04, 1.01378751e-04, 1.01378751e-04,
       1.01675623e-04, 1.02734324e-04, 1.07435144e-04, 1.07850919e-04,
       1.08379730e-04, 1.11405221e-04, 1.11637315e-04, 1.12643057e-04,
       1.13093629e-04, 1.15861430e-04, 1.15861430e-04, 1.15861430e-04,
       1.16621502e-04, 1.17148779e-04, 1.17148779e-04, 1.21654501e-04,
       1.21654501e-04, 1.21654501e-04, 1.21654501e-04, 1.21654501e-04,
       1.21654501e-04, 1.21654501e-04, 1.22298176e-04, 1.24357935e-04,
       1.24934402e-04, 1.28320802e-04, 1.29891525e-04, 1.30453562e-04,
       1.31253756e-04, 1.33059611e-04, 1.33536061e-04, 1.34338114e-04,
       1.34376541e-04, 1.35171668e-04, 1.35171668e-04, 1.35171668e-04,
       1.35171668e-04, 1.35171668e-04, 1.35171668e-04, 1.35171668e-04,
       1.35171668e-04, 1.35171668e-04, 1.35171668e-04, 1.35171668e-04,
       1.35171668e-04, 1.35171668e-04, 1.35171668e-04, 1.35171668e-04,
       1.35171668e-04, 1.35171668e-04, 1.35171668e-04, 1.35171668e-04,
       1.35544191e-04, 1.35966795e-04, 1.37987744e-04, 1.38570256e-04,
       1.38587394e-04, 1.39033716e-04, 1.42563869e-04, 1.42681205e-04,
       1.43122943e-04, 1.43294965e-04, 1.48688835e-04, 1.49303251e-04,
       1.49740707e-04, 1.51072303e-04, 1.52068127e-04, 1.52068127e-04,
       1.52068127e-04, 1.52068127e-04, 1.52068127e-04, 1.52068127e-04,
       1.52068127e-04, 1.52068127e-04, 1.52068127e-04, 1.52068127e-04,
       1.52068127e-04, 1.52573626e-04, 1.52619773e-04, 1.54481906e-04,
       1.54481906e-04, 1.54481906e-04, 1.54481906e-04, 1.54642825e-04,
       1.55447418e-04, 1.55504213e-04, 1.55844982e-04, 1.57267037e-04,
       1.57700279e-04, 1.59309466e-04, 1.59777677e-04, 1.60243832e-04,
       1.60516356e-04, 1.60783142e-04, 1.60918652e-04, 1.60918652e-04,
       1.62206002e-04, 1.62206002e-04, 1.62206002e-04, 1.62206002e-04,
       1.62206002e-04, 1.62206002e-04, 1.62206002e-04, 1.62206002e-04,
       1.62206002e-04, 1.62206002e-04, 1.62930136e-04, 1.63171514e-04,
       1.65038300e-04, 1.65111007e-04, 1.66365130e-04, 1.66365130e-04,
       1.68964585e-04, 1.68964585e-04, 1.68964585e-04, 1.68964585e-04,
       1.69098154e-04, 1.69504095e-04, 1.69627191e-04, 1.70372623e-04,
       1.72343877e-04, 1.72877449e-04, 1.72899466e-04, 1.73792145e-04,
       1.75011739e-04, 1.75723168e-04, 1.76667382e-04, 1.77381162e-04,
       1.77412814e-04, 1.77895570e-04, 1.79068561e-04, 1.80228891e-04,
       1.80228891e-04, 1.80228891e-04, 1.80228891e-04, 1.81414607e-04,
       1.81978006e-04, 1.82481752e-04, 1.82481752e-04, 1.82481752e-04,
       1.82481752e-04, 1.82481752e-04, 1.82481752e-04, 1.82481752e-04,
       1.84325002e-04, 1.85047845e-04, 1.85861044e-04, 1.86090148e-04,
       1.86479744e-04, 1.88020226e-04, 1.89676373e-04, 1.90280117e-04,
       1.92005210e-04, 1.92794418e-04, 1.94309273e-04, 1.97574228e-04,
       1.99066960e-04, 2.00529398e-04, 2.00709446e-04, 2.00992279e-04,
       2.01090299e-04, 2.01342149e-04, 2.02116305e-04, 2.03883933e-04,
       2.07956412e-04, 2.08458857e-04, 2.08464804e-04, 2.12673901e-04,
       2.12895377e-04, 2.14683618e-04, 2.16274669e-04, 2.16778806e-04,
       2.17902043e-04, 2.19164853e-04, 2.24511173e-04, 2.24766222e-04,
       2.29359020e-04, 2.29725137e-04, 2.36587671e-04, 2.39494976e-04,
       2.46071024e-04, 2.46333450e-04, 2.46746874e-04, 2.46889781e-04,
       2.49919046e-04, 2.50328537e-04, 2.52612797e-04, 2.53502075e-04,
       2.60040712e-04, 2.60126110e-04, 2.63598963e-04, 2.66349628e-04,
       2.66625560e-04, 2.66970234e-04, 2.80378808e-04, 2.82734072e-04,
       2.83079573e-04, 2.83576926e-04, 2.88711314e-04, 2.93290578e-04,
       2.93718888e-04, 2.97705268e-04, 3.06331560e-04, 3.08620946e-04,
       3.08765811e-04, 3.12285675e-04, 3.26187911e-04, 3.56662091e-04,
       3.61709371e-04, 3.93035681e-04, 4.15074504e-04, 4.38073914e-04,
       4.77823349e-04, 4.85789923e-04, 5.86548488e-04, 6.06692577e-04,
       6.55686563e-04, 7.42489055e-04, 1.10975936e-03, 1.34332459e-03,
       1.51346078e-03, 1.90601342e-03, 2.32720179e-03, 3.41064638e-03,
       3.65950993e-03, 1.01473548e-02, 9.36090799e-02])

In [14]:
trees = []

for alpha in ccps:
    moodel = DecisionTreeClassifier(ccp_alpha=alpha)
    model.fit(X_train, y_train)
    trees.append((model, alpha))

In [15]:
best_acc = 0
best_alpha = 0
for model, alpha in trees:
    curr_acc = model.score(X_test, y_test)
    if curr_acc > best_acc:
        best_acc = curr_acc
        best_alpha = alpha
print(best_alpha, best_acc)

0.0 0.856853203568532

In [30]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import GridSearchCV, RandomizedSearchCV

pipe = Pipeline([
    ("scaler", StandardScaler()),
    ("decision_tree", DecisionTreeClassifier())
])

param_grid = {
    # 'Decision_tree__criterion': ['gini', 'entropy'],
    'decision_tree__splitter': ['best', 'random'],
    'decision_tree__max_depth': [None, 3, 5, 7, 10, 15, 20],
    'decision_tree__min_samples_split': [2, 5, 10, 20],
    'decision_tree__min_samples_leaf': [1, 2, 5, 10],
    'decision_tree__max_features': [None, 'sqrt', 'log2'],
    'decision_tree__ccp_alpha': ccps
}

classiferCV = RandomizedSearchCV(
    estimator=pipe,
    param_distributions=param_grid,
    scoring="f1",
    cv=5,
    n_jobs=-1,
    n_iter=5000
)

classiferCV.fit(X_train, y_train)

y_pred = classiferCV.predict(X_test)

print("Accuracy:\t", accuracy_score(y_test, y_pred))
print("Recall:\t",  recall_score(y_test, y_pred))
print("Precision:\t", precision_score(y_test, y_pred))
print("F1 Scorce:\t", f1_score(y_test, y_pred))
print("CM:\n", confusion_matrix(y_test, y_pred))
print(classiferCV.best_params_)

Accuracy:	 0.8884833738848338
Recall:	 0.583941605839416
Precision:	 0.6976744186046512
F1 Scorce:	 0.6357615894039735
CM:
 [[1951  104]
 [ 171  240]]
{'decision_tree__splitter': 'best', 'decision_tree__min_samples_split': 20, 'decision_tree__min_samples_leaf': 10, 'decision_tree__max_features': None, 'decision_tree__max_depth': 3, 'decision_tree__ccp_alpha': np.float64(0.00017738116167568494)}